version: "3.7"

services:
  payment_database:
    image: mysql
    container_name: payment_database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=payment
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=payment
    ports: 
      - "3330:3306"
  rabbitmq:
    image: rabbitmq:3.9.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  app:
    build: .
    container_name: payment
    environment:
      - DATABASE_URL=mysql://root:123456@localhost:3330/payment?schema=publi
    volumes:
      - .:/usr/app
    network_mode: host
volumes:
  rabbitmq_data: